"use strict";
let lname = 'John';
lname = "Santosh";
let newname = lname.toUpperCase();
console.log(newname);
let age;
age = 25;
age = 25.5;
let dob = "25";
let result = parseInt(dob);
console.log(result);
